### ISSUE TITLE
NewClient expects Interface http.RoundTripper where it actually needs http.Transport

### ISSUE THREAD

**Issue by vinzenz** [kolo/xmlrpc#28]
`http.RoundTripper` is the expected parameter type for the `transport` parameter of `NewClient`

However `clientCodec.Close` casts it to `http.Transport` and breaks the application using `xmlrpc.NewClient` if it is not passing a `http.Transport`

**Comment by ibukanov** [comment]
This hit me as well - I use a custom RoundTripper to add headers to the request.
