### ISSUE TITLE
Return unknown types as interface?

### ISSUE THREAD

**Issue by edgard** [kolo/xmlrpc#35]
Is this possible? I'm having a lot of issues with python xmlrpc servers, specially with date fields.

I'd send a pull request if I could, but I'm just starting with go, so no cookie. :(

**Comment by kolo** [comment]
I'm not sure. Please explain in more details what problem you are trying to solve? Maybe there are another solutions available.

**Comment by edgard** [comment]
I'm trying to process a call that returns a timestamp (as in python/posix timestamp), but it's not being recognized as a valid type, so the call is failing.

**Comment by kolo** [comment]
Can you show a response from the server?

**Comment by edgard** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
<params>
<param><value><i8>1428613051</i8></value></param>
</params>
</methodResponse>
```

So, I suppose just need to add an i8 type?, eg [this](https://github.com/bittersweet/xmlrpc/commit/64c9915d870a210ec1ed0f6534c2dfcffe857495)?

**Comment by kolo** [comment]
I pushed commit 0826b98 which adds support of i8 type. Please close the issue if this is enough to solve your problem.

**Comment by edgard** [comment]
Works like a charm, thank you very much! :+1:
