### ISSUE TITLE
Cannot decode an array response

### ISSUE THREAD

**Issue by alecthegeek** [kolo/xmlrpc#43]
When my server responds with the following

``` xml
<methodResponse>
    <params>
        <param>
            <value>
                <array>
                    <data>
                        <value>
                            Account1
                            </value>
                        <value>
                            Account2
                            </value>
                        </data>
                    </array>
                </value>
            </param>
        </params>
    </methodResponse>
```

I get an error message `reading body error: type mismatch - can't unmarshal interface to string`. Simpler responses (e.g. a string) can be decoded fine.

Does anyone know if this case does work?  Looking at the decoder I see there is a case for strings with no type (default to string).  I'm not sure how to get the tests to run.

Thanks

**Comment by alecthegeek** [comment]
OK -- I gave up and moved to github.com/divan/gorilla-xmlrpc/xml

**Comment by kodburn** [comment]
```
<data>
    <value>
       <string>Account1</string>
    </value>
    <value>
      <string>Account1</string>
    </value>
</data>
```
Should work fine.
