### ISSUE TITLE
Can't retrieve info on the top 10 Python packages

### ISSUE THREAD

**Issue by cclauss** [kolo/xmlrpc#47]
I can make this work in Python but I am struggling to replicate in Go...

https://github.com/cclauss/go-hacks/blob/master/pypiTop10.go  Any tips?

https://warehouse.pypa.io/api-reference/xml-rpc/

**Comment by oz** [comment]
In your code `result` is an array, but the Go library expects a slice type, so change its type. Maybe:

```go
var result []interface{}
```

**Comment by cclauss** [comment]
Thanks much @oz !!

[var result \[\]interface{}](https://github.com/cclauss/go-hacks/blob/master/pypiTop10.go#L20) lets me get back 10 items when I request 10.  Nice forward progress!

My remaining problem is to [convert each item returned into type pkgInfo](https://github.com/cclauss/go-hacks/blob/master/pypiTop10.go#L31).
