### ISSUE TITLE
"connection is shut down" error raises if previous request has failed

### ISSUE THREAD

**Issue by kolo** [kolo/xmlrpc#6]
User will get "connection is shut down" error when it tries to send request if previous one has failed.

**Comment by sonic0002** [comment]
hello, admin, it seems we see that the same issue occured again with latest codebase, originally you guys have fixed this, but later it seemed you added some code which reintroduced the issue again?

The code which caused this same issue now is the below code block(in client.go) per our understanding .

```
	if httpResponse.StatusCode < 200 || httpResponse.StatusCode >= 300 {
		return fmt.Errorf("request error: bad status code - %d", httpResponse.StatusCode)
	}
```
Based on our checking so far, when error returned from above code, the caller for loop breaks and client.shutdown is set to true and all following requests get failed.

Can you confirm this issue and if yes any plan to fix it? Thanks.

@kolo @miracle2k

**Comment by engAmirEng** [comment]
hey, what is the state of this issue, i'm facing it too
