### ISSUE TITLE
throwing an error on ignored fields

### ISSUE THREAD

**Issue by isaacwein** [kolo/xmlrpc#81]
the xmlrpc encoder is throwing an error on ignored fields 

`xmlrpc_test.go:23: err: xmlrpc encode error: unsupported type`
````go

import (
	"context"
	"github.com/kolo/xmlrpc"
	"testing"
)

type Req struct {
	Id        int             `xmlrpc:"id"`
	Name      string          `xmlrpc:"name"`
	CTX       context.Context `xmlrpc:"-"` // this field is making the error
	OtherData struct{}        `xmlrpc:"-"`
}

func TestName(t *testing.T) {
	call, err := xmlrpc.EncodeMethodCall("test", &Req{
		Id:   1,
		Name: "test",
		CTX:  context.Background(),
	})
	if err != nil {
		t.Fatalf("err: %s", err.Error())
	}
	t.Logf("xml-rpc call: %s", call)
}
````
[playground](https://goplay.tools/snippet/h7FvDjNCzL2)

**Comment by icholy** [comment]
This library doesn't support ignoring fields with `-` like `encoding/json` does. Adding support would technically be a backwards incompatible change, but I'd be surprised if anyone was actually affected. @kolo thoughts?

**Comment by isaacwein** [comment]
Why would it be a backward incomparable how can you use`xmlrpc”-“` at all?
Or may you can add a new suffix like `xmlrpc=“,ignore”`

**Comment by icholy** [comment]
Currently, if you define a struct with a `-` field tag, it will use `-` as the field name in the generated xml:

For example:

``` go
type S struct {
    Name string `xmlrpc:"-"`
}
```

Will encode like this:

``` xml
<value><struct><member><name>-</name><value><string>test</string></value></member></struct></value>
```

So adding support for `-` can potentially change the behaviour of existing code. In practice, I think that's very unlikely. I'm leading towards simply adding support for `-`.

**Comment by isaacwein** [comment]
Ok, thanks for the clarification.

As of the JSON standard

As a special case, if the field tag is "-", the field is always omitted.
Note that a field with name "-" can still be generated using the tag "-,".


https://pkg.go.dev/encoding/json#:~:text=as%20a%20special%20case%2C%20if%20the%20field%20tag%20is%20%22%2D%22%2C%20the%20field%20is%20always%20omitted.%20note%20that%20a%20field%20with%20name%20%22%2D%22%20can%20still%20be%20generated%20using%20the%20tag%20%22%2D%2C%22
.

**Comment by isaacwein** [comment]
i think if a tag is`xmlrpc:"-,"` the key should be `<name>-</name>` like json, not `<name>-,</name>` comma is a special character it is used for additional info about the tag `xmlrpc:"key,omitempty"`


https://goplay.tools/snippet/aalpRUBlTbJ

**Comment by isaacwein** [comment]
thanks alot for adding support for this it helped a lot
